use crate::{ContentKind as C, ExtensionResolver, FileSupportPatch as P, FileSupportResolver};
macro_rules! r {
    ($e:expr,$k:expr,$m:expr,$i:expr,$d:expr) => {
        &ExtensionResolver {
            extensions: $e,
            patch: P {
                language: None,
                content_kind: Some($k),
                mime: Some($m),
                icon_name: Some($i),
                display_name: Some($d),
                role: crate::RolePatch::Keep,
            },
        }
    };
}
pub(crate) static RESOLVERS: &[&dyn FileSupportResolver] = &[
    r!(
        &["apng"],
        C::Image,
        "image/apng",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["avif"],
        C::Image,
        "image/avif",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["bmp"],
        C::Image,
        "image/bmp",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["dds"],
        C::Image,
        "image/vnd.ms-dds",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["gif"],
        C::Image,
        "image/gif",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["heic"],
        C::Image,
        "image/heic",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["heif"],
        C::Image,
        "image/heif",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["jp2"],
        C::Image,
        "image/jp2",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["ico"],
        C::Image,
        "image/vnd.microsoft.icon",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["jpg", "jpeg"],
        C::Image,
        "image/jpeg",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["jxl"],
        C::Image,
        "image/jxl",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["pbm"],
        C::Image,
        "image/x-portable-bitmap",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["pgm"],
        C::Image,
        "image/x-portable-graymap",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["ppm"],
        C::Image,
        "image/x-portable-pixmap",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["pnm"],
        C::Image,
        "image/x-portable-anymap",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["png"],
        C::Image,
        "image/png",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["qoi"],
        C::Image,
        "image/qoi",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["tif", "tiff"],
        C::Image,
        "image/tiff",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["tga"],
        C::Image,
        "image/x-tga",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["webp"],
        C::Image,
        "image/webp",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["xbm"],
        C::Image,
        "image/x-xbitmap",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["xpm"],
        C::Image,
        "image/x-xpixmap",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["dng"],
        C::Image,
        "image/x-adobe-dng",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["cr2"],
        C::Image,
        "image/x-canon-cr2",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["erf"],
        C::Image,
        "image/x-epson-erf",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["exr"],
        C::Image,
        "image/exr",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["mrw"],
        C::Image,
        "image/x-minolta-mrw",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["orf"],
        C::Image,
        "image/x-olympus-orf",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["pef"],
        C::Image,
        "image/x-pentax-pef",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["raw"],
        C::Image,
        "image/x-raw",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["srf"],
        C::Image,
        "image/x-sony-srf",
        "image-x-generic-symbolic",
        "Image"
    ),
    r!(
        &["aac"],
        C::Audio,
        "audio/aac",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["aif", "aifc", "aiff"],
        C::Audio,
        "audio/aiff",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["flac"],
        C::Audio,
        "audio/flac",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["m4a"],
        C::Audio,
        "audio/mp4",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["mid", "midi"],
        C::Audio,
        "audio/midi",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["mp3"],
        C::Audio,
        "audio/mpeg",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["oga", "ogg"],
        C::Audio,
        "audio/ogg",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["opus"],
        C::Audio,
        "audio/opus",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["wav"],
        C::Audio,
        "audio/wav",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["weba"],
        C::Audio,
        "audio/webm",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["wma"],
        C::Audio,
        "audio/x-ms-wma",
        "audio-x-generic-symbolic",
        "Audio"
    ),
    r!(
        &["3gp"],
        C::Video,
        "video/3gpp",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["avi"],
        C::Video,
        "video/x-msvideo",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["flv"],
        C::Video,
        "video/x-flv",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["m4v"],
        C::Video,
        "video/x-m4v",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["mkv"],
        C::Video,
        "video/x-matroska",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["mov"],
        C::Video,
        "video/quicktime",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["mp4"],
        C::Video,
        "video/mp4",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["mpeg", "mpg"],
        C::Video,
        "video/mpeg",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["ogv"],
        C::Video,
        "video/ogg",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["webm"],
        C::Video,
        "video/webm",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["wmv"],
        C::Video,
        "video/x-ms-wmv",
        "video-x-generic-symbolic",
        "Video"
    ),
    r!(
        &["eot"],
        C::Font,
        "application/vnd.ms-fontobject",
        "text-x-generic-symbolic",
        "Font"
    ),
    r!(
        &["otf", "otc"],
        C::Font,
        "font/otf",
        "text-x-generic-symbolic",
        "Font"
    ),
    r!(
        &["ttf", "ttc"],
        C::Font,
        "font/ttf",
        "text-x-generic-symbolic",
        "Font"
    ),
    r!(
        &["woff"],
        C::Font,
        "font/woff",
        "text-x-generic-symbolic",
        "Font"
    ),
    r!(
        &["woff2"],
        C::Font,
        "font/woff2",
        "text-x-generic-symbolic",
        "Font"
    ),
];
