[package]
name = "craic-ui-containers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
craic-system.workspace = true
log.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
adw.workspace = true
craic-vcs.workspace = true
craic-ui-core.workspace = true
craic-ui-editor.workspace = true
gtk.workspace = true
