[package]
name = "craic-ui-gtk-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
adw.workspace = true
cairo.workspace = true
craic-app-core.workspace = true
craic-language.workspace = true
craic-file-support.workspace = true
craic-project.workspace = true
craic-platform.workspace = true
craic-render-skia.workspace = true
craic-system.workspace = true
craic-vcs.workspace = true
gtk.workspace = true
libc.workspace = true
log.workspace = true
moka.workspace = true
regex.workspace = true
tokio.workspace = true
